// <auto-generated />
using System;
using YoursTruly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace YoursTruly.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921011839_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("YoursTruly.Data.Entities.ContactPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AddedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AreaCodeAssumed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EnteredInLcrOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastSeenInLcrOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Normalized")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Kind");

                    b.HasIndex("PersonId", "Kind", "Normalized")
                        .IsUnique()
                        .HasFilter("\"Normalized\" IS NOT NULL");

                    b.HasIndex("Source", "EnteredInLcrOn", "LastSeenInLcrOn");

                    b.ToTable("ContactPoints");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AddedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeactivatedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReactivatedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportedAt");

                    b.HasIndex("Sha256");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.MessageBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudienceDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceRecordingPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("MessageBatches");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.MessageDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CostMicros")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("MessageBatchId", "Status");

                    b.ToTable("MessageDeliveries");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DeactivatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FirstSeenOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LastSeenOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LcrEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("LcrPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredChannel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ward")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Ward");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("People");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.PersonChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportRunId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonChanges");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.ContactPoint", b =>
                {
                    b.HasOne("YoursTruly.Data.Entities.Person", "Person")
                        .WithMany("ContactPoints")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.MessageDelivery", b =>
                {
                    b.HasOne("YoursTruly.Data.Entities.MessageBatch", "MessageBatch")
                        .WithMany("Deliveries")
                        .HasForeignKey("MessageBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoursTruly.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageBatch");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.PersonChange", b =>
                {
                    b.HasOne("YoursTruly.Data.Entities.ImportRun", "ImportRun")
                        .WithMany("Changes")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YoursTruly.Data.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRun");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.ImportRun", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.MessageBatch", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("YoursTruly.Data.Entities.Person", b =>
                {
                    b.Navigation("ContactPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
